// <auto-generated />
using DAL.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230201143825_INITAL")]
    partial class INITAL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MODELS.Models.Asignaciones", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AsignacionFechaInicio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("AsignacionNo")
                        .HasColumnType("int");

                    b.Property<int>("AsignacionNoDias")
                        .HasColumnType("int");

                    b.Property<int>("EdificioNumero")
                        .HasColumnType("int");

                    b.Property<int>("TrabajadorNumero")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("MODELS.Models.Edificios", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("EdificioDireccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EdificioNumero")
                        .HasColumnType("int");

                    b.Property<int>("NivelCalidad")
                        .HasColumnType("int");

                    b.Property<string>("TipoEdificio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Edificios");
                });

            modelBuilder.Entity("MODELS.Models.Trabajadores", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Oficio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrabajadorNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrabajadorNumero")
                        .HasColumnType("int");

                    b.Property<int>("TrabajadorSupervisor")
                        .HasColumnType("int");

                    b.Property<float>("TrabajadorTarifa")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Trabajadores");
                });
#pragma warning restore 612, 618
        }
    }
}
